### ISSUE TITLE
Get search feature working.

### ISSUE THREAD

**Issue by moylanm** [osu-cascades/rfr-cookbook#1]

**Comment by moylanm** [comment]
I tried getting the [search feature](https://help.syncfusion.com/flutter/pdf-viewer/text-search#how-to-create-and-display-a-custom-search-toolbar-with-the-search-features) to work but it wasn't capturing anything. I also noticed this package is still in beta so there are certainly no guarantees. We may have to find our own way of searching through pdf files.

**Comment by adriannagilmore** [comment]
Alright. I will do some research and try something new this week.

**Comment by adriannagilmore** [comment]
Search working with hardcoded list. Still need to get it to pull from the firebase.

**Comment by adriannagilmore** [comment]
created "search" for working on search feature

**Comment by adriannagilmore** [comment]
Closing this issue to make several smaller issues to work on
